### ISSUE TITLE
meta : git 자체를 배울때는 프로그래밍 언어보다 책을 같이 써보는것도 좋다.

### ISSUE THREAD

**Issue by khw7096** [khw7096/pandoc#2]
git 자체를 배울때는 프로그래밍 언어보다 책을 같이 써보는것도 좋다.

**Comment by suinbaek** [comment]
예를 들면 ?

**Comment by khw7096** [comment]
코드에 집중하기 보다는 github 에서 같이 책을 쓰는 느낌이 더 강하니까요. 프로그래밍 언어보다는 글이 더 편하듯이..
